### PR TITLE
Update link to emerging standards doc

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by wkeese** [comment]
Ah now I see why you were asking about that google doc.

**Comment by cjolif** [comment]
Maybe it could also point to: http://ibm-js.github.io/delite/ other than that I think this change should go in as the document currently linked is not as up to date at the other references?

**Comment by cjolif** [comment]
@dandv not that this is really needed for such a limited change in particular to the doc but do you have a Dojo CLA? (http://dojofoundation.org/about/cla)

**Comment by dandv** [comment]
@cjolif: just signed.

**Comment by wkeese** [comment]
I was toying with updating https://docs.google.com/document/d/1kqe3Oq7W6lg-JY_iqMl5G7SxGTD0uQ6FFIoP4KPAkUw but in lieu of that, I agree the README should point to  http://ibm-js.github.io/delite/  and also http://ibm-js.github.io/2014/07/18/delite-and-deliteful.html.

**Comment by wkeese** [comment]
OK, thanks, I updated the README in 626ac4294013a45feca93555455d888d28963095, removing that link.

**Pull request closed without merging**
