### PR TITLE
New templates for documentation

### PR DESCRIPTION
**Pull request by clmath**
This PR contains the templates used in https://github.com/ibm-js/delite/pull/368.

__Warning__: this PR MUST NOT be merged until the new doc from https://github.com/ibm-js/delite/pull/368 is committed and deployed. Otherwise it will break ibm-js.github.io

### CODE REVIEW

**Comment by wkeese** [comment]
> Warning: this PR MUST NOT be merged until the new doc from #368 is committed and deployed. Otherwise it will break ibm-js.github.io

I'm not following.  It seems like #368 and #369 should be checked in together, and then the new gh-pages branch should be generated.   I forget how to do that though...

You can push these changes yourself, or if you don't have write permission then let me know what to do.

**Comment by cjolif** [comment]
#369 is not against master but against gh-pages thus the fact it can break gh-pages. @clmath process is correct. First #368 needs to be committed to master (it can't break doc as it is not deployed), then when we will deploy we will need to also commit #369. Basically #368 can be committed any time, #369 has to wait the release time.

**Comment by wkeese** [comment]
Ah I didn't realize that #369 is against gh-pages.  Should I push #368 now, or are you guys handling everything?

**Comment by cjolif** [comment]
Feel free to merge #368 if you want, otherwise we will look into merging it next week.

**Pull request merged**
