### PR TITLE
Tutorial code and document updates

### PR DESCRIPTION
**Pull request by lbod**
Note that https://github.com/ibm-js/delite-tutorial/ has been updated with the runnable code e.g. http://ibm-js.github.io/delite-tutorial/runnable/introduction-part5/samples/BlogPost.html

I'd thought about running a build because the runnable code loads a bit slow, however the build step is covered in deliteful and I didn't want to replicate that, what do you think? I've ran the docs through jekyll and it looked ok.

Also, I'll add a further PR to the gh-pages branch of delite to update the tutorial link to index.md

### CODE REVIEW

**Comment by wkeese** [comment]
Seems reasonable.  I guess when I push this I should squash all the commits together?

@cjolif did you or your team have any comments?

**Comment by lbod** [comment]
Sorry I probably should have squashed them more myself. There were many more commits as I worked through splitting the doc up but I've obviously left unimportant commits in-place. Let me know if you want me to repush

**Comment by wkeese** [comment]
It's fine, I can squash them.

**Comment by cjolif** [comment]
My only comment is that for next release there will be more questions in the delite generator so that part should probably updated once again when the generator will be released (hopefully soon).

**Comment by wkeese** [comment]
OK, well I pushed this as 8710cbc8ba2ae4a027021b66d588eecacea72aea and we can do the delite generator changes in a separate commit (although apparently you've just finished updating generator)?

**Comment by cjolif** [comment]
> (although apparently you've just finished updating generator)?

Yes I finished that yesterday night.

**Pull request closed without merging**
