### PR TITLE
Emit delite-add-child event for children added to Container.

### LINKED ISSUE #403: Container: emit delite-add-child, delite-remove-child events
Feature to be used by deliteful/TabBar.

cc @cjolif

### PR DESCRIPTION
**Pull request by wkeese**
Fixes #403.

@cjolif, how's this look?   It's for TabBar to use.

### CODE REVIEW

**Comment by cjolif** [comment]
For consistency reasons should we do the same on remove?

**Comment by wkeese** [comment]
Agreed.  I added that in 936e34fef0e230603eda655f6a17cf7002771dc0.   Anything else?

**Comment by cjolif** [comment]
> Anything else?

No I should be all set. But that's just looking at the PR code, I have not yet tested on my actual use-case however but I'm confident it should solve it.

**Comment by wkeese** [comment]
OK.   I pushed as 666303a3f552f584a0f9b3f4f65f153677f7b711.

**Pull request closed without merging**
