### PR TITLE
Tracking the changes of 'dir'

### PR DESCRIPTION
**Pull request by semion1956**
This is some workaround, proposed in order to solve the problem with tracking the changes of property 'dir' (issue #340). Reason of the problem described in #404 by Bill: "There are some platforms where the custom setter for a native property won't get called, and thus we get no notification that it changed."
There are 3 options for 3 types of platform:
1) If platform supports variant of MutationObserver, create correponding observer;
2) else if platform supports DOMAttrModidfied event, add listener for this event;
3) else add listener for DOMSubtreeModified event (direct getters for 'dir' will not work correctly, but isLeftToRight() can be modified to return correct results).

### CODE REVIEW

**Comment by wkeese** [comment]
FYI, I'm working on more general code in #355, to hopefully track changes to all attributes with shadow properties (like `dir` and `tabIndex` and `title`).

**Comment by wkeese** [comment]
About DOMSubTreeModified: I see that we need this for Android < 4.4.   However, it's not working well for me.  Specifically, I only get notified when an attribute is added, not when it's changed.  In the code below, I only get one notification:

```xml
<html>
	<body>
		<div id="log">
			log:<br>
		</div>
		<div id="test" foo="bar">test</div>
		<script>
			test.onpropertychange = function () {
				log.innerHTML += "onpropchange<br>";
			};
			test.addEventListener("DOMAttrModified", function () {
				log.innerHTML += "DOMAttrModified<br>";
			});
			test.addEventListener("DOMSubtreeModified", function (evt) {
				log.innerHTML += "DOMSubTreeModified<br>";
			});

			log.innerHTML += "set initial dir to rtl<br>";
			test.dir = "rtl";

			log.innerHTML += "change dir from rtl to ltr<br>";
			test.dir = "ltr";

			log.innerHTML += "change dir back to rtl<br>";
			test.dir = "rtl";
		</script>
	</body>
</html>
```

How about you?

**Comment by semion1956** [comment]
Yes, this notification is received, when attribute is added or removed. That is why I save value of the attribute and remove attribute itself immediately after its appearance. Correct behavior is achieved by using corresponding style. I see this as some workaround for handling *dir* only.

**Comment by wkeese** [comment]
I see, thanks.   So in that case there's no `dir` setting on the root node (except for 1ms)?  It makes sense only if the widget handles the `dir` setting on a sub-node.   It is though the strategy Widget.js uses for `tabIndex` but only *when there's a custom setter defined for `tabIndex`.

**Comment by wkeese** [comment]
PS: Oh OK, now I understand how you are setting the style `direction` attribute.  OK, interesting.

**Comment by wkeese** [comment]
I made a different checkin (f505144) w/the same functionality, so closing this ticket.

**Comment by semion1956** [comment]
Thank you, Bill. The only question is platform like Safari for Windows (5.1), where any MutationObserver isn't defined. Do you plan to handle somehow this case too? (BTW, Safari reports about error: ```Can't find variable WebKitMutationObserver``` if it isn't written as ```window.WebKitMutationObserver```)

**Comment by cjolif** [comment]
For what it worth's Safari for Windows is not supported.

**Comment by wkeese** [comment]
Also, note that for most of the platforms it uses a custom setter.   MutationObserver is actually the fallback aka workaround.

**Pull request closed without merging**
