### PR TITLE
This is the first commit for the delite tutorial. 

### PR DESCRIPTION
**Pull request by lbod**
Note that after @cjolif comments re where the tuturial docs and runnable code should be, the history comments of this PR are actually at https://github.com/ibm-js/delite-tutorial/pull/1; I'll close that PR.
This is in progress, this doc will be split up once the runnable code is added to https://github.com/ibm-js/delite-tutorial.

I'll start to work on the runnable code for https://github.com/ibm-js/delite-tutorial

### CODE REVIEW

**Comment by wkeese** [comment]
I guess this is ready to push then, except that we should add the tutorial to index.md.  @cjolif?

**Comment by cjolif** [comment]
Looks good to me indeed. For linking into it instead of having an entry in index.md I will add a top level tutorial tab just as for deliteful see:

image

I will do that once the tutorial is committed. So I think adding to index.md is not needed.

**Comment by cjolif** [comment]
We should also put a YAML header, like in deliteful tutorial:

```
---
layout: tutorial
title: Deliteful Tutorial Part 1
---
```

**Comment by wkeese** [comment]
OK, I pushed this, thanks for all the work!  I updated the head as @cjolif mentioned above.

**Pull request closed without merging**
