### PR TITLE
document delite and deliteful's i18n support

### PR DESCRIPTION
**Pull request by wkeese**
Here's my attempt to document delite and deliteful's i18n support, in particular that part about the current restrictions of what isn't supported, as I promised to do in a meeting with @cjolif and @pruzand.   The document isn't really specific to delite but I didn't know a better place to put it.

Please review and let me know corrections for any mistakes, or terminology, including the title itself (should it be "internationalisation support"?).

There are a few possible future enhancements for delite, but for now I'm just documenting the **current** state.   For the record, known possible future enhancements/changes are:

* since an app can set `dir` on `<html>` or `<body>`, shouldn't it be able to set `textdir` too?
* @semion1956 is working on a PR to enable inheriting `dir` from ancestor nodes other than `<html>` or `<body>`.   Related to that, if `dir` can be inherited from any ancestor node, then what about `textdir`?
* splitting `has("bidi")` into two separate flags, one for "advanced features" (whatever that means) and one for "basic features".   also, possibly renaming `has("bidi")`. (ibm-js/deliteful#462)

After this doc is committed, the PR's for future enhancements should update this document.

PS: @clmath, AFAICT the documentation for i18n! doesn't state how it determines the browser's locale.  I'm guessing it's from the metadata passed over HTTP (requested languages or whatever it's called), but maybe it's from looking at the `lang` attribute on `<html>` or `<body>`?   Let me know the algorithm so I can document it here.

### CODE REVIEW

**Comment by cjolif** [comment]
nls is often use a shortcut for translations while here we talk about more than that, wouldn't it be better to call the file & document "globalization" ?

**Comment by wkeese** [comment]
Sure, either "globalization" or "internationalization".

I should probably also add a section about writing widgets, telling people to leverage i18n! and ecma402.

**Comment by cjolif** [comment]
From what I heard globalization seems more correct, @pdardailler any feedback here?

**Comment by clmath** [comment]
@wkeese It is (quickly) described in the i18n doc as a note in the add a locale part. Maybe it is worth its own section ?

>The plugin uses the browser's `navigator.language` or `navigator.userLanguage` property to determine the required locale. Then it selects the most suitable locale from the root bundle. The locale can also be set using RequireJS config:

```
require.config({
	config: {
		// Set locale to fr
        "requirejs-dplugins/i18n": {
			locale: "fr"
		}
	}
});
```

To be totally clear, the order is:
requirejs module config > requirejs global config (to support people coming from requirejs i18n) > navigator.language > navigator.userLanguage > root

Also, unfortunately the value in the accept language header of the http request is not available in JS. So the preferred way to set a locale is to use server-side detection to use the accept language header and then force this locale in requirejs module config.

**Comment by pdardailler** [comment]
Regarding the use of i18n vs g11n. In IBM, we are supposed to use g11n to mean multi-cultural support + translation. In this context, i18n = mcs, but g11n team wants us to use mcs, and not i18n.
In your outside world, you should use what you think is the most understandable or the most appropriate term for your users. As you are in a developer world, I guess that everyone is familiar with i18n. You can try to google it to see what's coming out.
As a summary, it depends what hat you are wearing ;-)

**Comment by wkeese** [comment]
@clmath - OK thanks.   I think it would be good for the locale detection to have its own section.   Actually, in the table of contents of https://github.com/ibm-js/requirejs-dplugins/blob/master/docs/i18n.md you have an item called "Locale detection", but it's a broken link.   So you should fix that.   I think it would also be good to start the document w/a more specific description of what the plugin does, rather than just saying that it's "a RequireJS plugin which provides support for localized string."

@pdardailler - OK, thanks.  Sounds like a toss up.   I'll call the page "Internationalization and Localization" since that's the term Wikipedia uses.

**Comment by wkeese** [comment]
OK, I pushed this as 3024e7a438310fefbe8add252c8e37b3ef2c80b4.

**Comment by semion1956** [comment]
To the one of @wkeese previous comments:
> known possible future enhancements/changes are:
* since an app can set dir on <html> or <body>, shouldn't it be able to set *textdir too?
* if *dir can be inherited from any ancestor node, then what about *textdir?

We think that inheritance of *textdir doesn't make sence, because unlike *dir it (in general) should not affect all the contents of the ancestor node. Without possibility of inheritance setting *textdir (which BTW doesn't exist in HTML5 spec) on <html> or <body> seems unnecessary.

>splitting has("bidi") into two separate flags, one for "advanced features" (whatever that means) and one for "basic features". also, possibly renaming has("bidi")

We don't think, that support of basic bidi features requires some specific configuration.
We are fully satisfied with the name "bidi".

**Comment by wkeese** [comment]
> Without possibility of inheritance setting *textdir (which BTW doesn't exist in HTML5 spec) on `<html>` or `<body>` seems unnecessary.

OK, I'm surprised to hear you say that.   The issue came up when I was trying to document typical bidi-related scenarios.   I thought the most common case would be when the boilerplate is in English but the user data is in an RTL script like Hebrew.   In that case IIUC the application needs to set textdir on every widget, right?

**Comment by semion1956** [comment]
Talking about *textdir*, the most common bidi-related scenario is the case, when application displays the text with different base direction. If user data is "pure" RTL but boilerplate is in English, this most probably means globalization problems and should not be considered as a rule. But even such "problematic" applications almost certainly show not only RTL user data, but also some LTR data (given from not translated resources) like labels or messages. 

Need in *textdir* appears when some segments of the text can't be displayed properly with the default base text direction, set by application's boilerplate. We see it as some internal, widget-specific property, which can affect only some parts of some widgets, containing text. That is why we don't see many sense in inheritance of this property. If something like this will be required in some specific case for some specific application, application can do this itself.

**Comment by wkeese** [comment]
OK, thanks.   About your other comment:

> We don't think, that support of basic bidi features requires some specific configuration.

Yes, you wrote this in ibm-js/deliteful#462.  But please update that ticket to list what "basic bidi features" are.    I suspect the list is RTL GUI (implemented mainly by RTL CSS rules) and proper keyboard handling,

**Pull request closed without merging**
